lambda-error-sns-sender/__init__.py,sha256=oUhku7JWEMCtmsGgj3dh7LcCsK19Z5-wPCGHvX4YApU,24168
lambda-error-sns-sender/py.typed,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
lambda-error-sns-sender/_jsii/__init__.py,sha256=OToE9ec1L1FrZx1Wb0TUBJFpYEZsp16BcyaNjw8znu4,428
lambda-error-sns-sender/_jsii/lambda-error-sns-sender@0.0.35.jsii.tgz,sha256=k0LwgKBw5Qa5ZCtGt__FYTW7hDkXGsejtqv4F_jASY0,30327
lambda_error_sns_sender-0.0.35.dist-info/LICENSE,sha256=z8d0m5b2O9McPEK1xHG_dWgUBT6EfBDz6wA0F7xSPTA,11358
lambda_error_sns_sender-0.0.35.dist-info/METADATA,sha256=-WmInyVzVBvdeRzxvA2R06n9AnfojKOmjdCyDgRXtPA,1229
lambda_error_sns_sender-0.0.35.dist-info/WHEEL,sha256=5sUXSg9e4bi7lTLOHcm6QEYwO5TIF1TNbTSVFVjcJcc,92
lambda_error_sns_sender-0.0.35.dist-info/top_level.txt,sha256=FkMA9jPLJsN588vpcg5IZxGjGTXyTWVbDBZNa2cu0yI,24
lambda_error_sns_sender-0.0.35.dist-info/RECORD,,
